name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx run uv download.py
      - run: pipx run uv build.py
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl
